# Generated by Django 6.0.3 on 2026-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectfile',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
